# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-18 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='text_name',
            new_name='text_name1',
        ),
    ]
