# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-09 06:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TextApp', '0002_auto_20161018_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='audio_file',
            field=models.FileField(default=datetime.datetime(2016, 11, 9, 6, 39, 33, 104095, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='audio_title',
            field=models.CharField(default=datetime.datetime(2016, 11, 9, 6, 40, 19, 376040, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
